version: '3'
services:
  flask:
    container_name: flask
    build: .
    ports:
      - 5555:5555
    restart: always
    depends_on:
      - postgres
    environment:
        DB_USERNAME: test
        DB_PASSWORD: qweqwe][p][p

  postgres:
    environment:
      DATABASE_PORT: 5432
      DATABASE_DIALECT: postgresql
      POSTGRES_DB: flaskdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: qweqwe][p][p
    container_name: postgres
    image: postgres:14
    volumes:
       - flaskdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tmpruler@ya.ru
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
volumes:
    flaskdb:
      driver: local
    pgadmin:
      driver: local
