version: '3.9'
services:
  flask:
    container_name: flask
    build: .
    ports:
      - 5555:5555
    restart: always
    depends_on:
      - postgres
    environment:
        DB_USERNAME: test
        DB_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_user_password
  postgres:
    environment:
      DATABASE_PORT: 5432
      DATABASE_DIALECT: postgresql
      POSTGRES_DB: flaskdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_user_password
    container_name: postgres
    image: postgres:14
    volumes:
       - flaskdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tmpruler@ya.ru
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_default_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    secrets:
      - pgadmin_default_password
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
secrets:
  db_user_password:
    file: ./secrets/db_user_password.txt
  pgadmin_default_password:
    file: ./secrets/pgadmin_default_password.txt
volumes:
    flaskdb:
      driver: local
    pgadmin:
      driver: local
